# Generated by Django 6.0.7 on 2026-07-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_image',
            field=models.ImageField(blank=True, null=True, upload_to='song_covers/'),
        ),
    ]
